import Head from 'next/head';
import { useRouter } from 'next/router';
import DetailAdvert from '../../../components/DetailAdvert/DetailAdvert';
import { useEffect, useState } from 'react';
import { deleteAdvert, editAdvert, getAdvertById } from '../../../api/Adverts';
import PageLayout from '../../../components/PageLayout/PageLayout';
import { Button, Modal } from 'antd';
import AdvertDataForm from '../../../components/AdvertDataForm/AdvertDataForm';

export default function AdvertPage() {
  const router = useRouter();
  const { id } = router.query;
  const [{advert,isOwnerView}, setAdvertData] = useState({
    advert: null,
    isOwnerView: false,
  });
  const [isModalVisible, setIsModalVisible] = useState(false);
  useEffect(() => {
    if (id) {
      getAdvert(id);
    }
  }, [id]);
  async function getAdvert(id: string) {
    const advert = await getAdvertById(id);
    setAdvertData((state) => ({
      advert: advert.ad,
      isOwnerView: advert.isowner || false,
    }));
  }
  const onDelete = () => {
    deleteAdvert(id);
    router.push('/adverts');
  };
  const onEdit = () => {
    setIsModalVisible(true);
  };
  const handleOk = (data) => {
    editAdvert(id,data);
    setIsModalVisible(false);
    getAdvert(id);
  };
  const handleCancel = () => {
    setIsModalVisible(false);
  };
  return (
    <PageLayout>
      <Head>
        <title>Объявление</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DetailAdvert
        onDelete={onDelete}
        onEdit={onEdit}
        advert={advert}
        isOwnerView={isOwnerView}
      />
      <Modal
        title='Редактирование объявления'
        visible={isModalVisible}
        onCancel={handleCancel}
        footer={[
          <Button color='red' key='cancel' onClick={handleCancel}>
            Отмена
          </Button>,
        ]}
      >
        {advert && <AdvertDataForm onFinish={handleOk} initialData={advert}  buttonText='Сохранить' />}
      </Modal>
    </PageLayout>
  );
}
