import type { NextPage } from 'next'
import Head from 'next/head'
import AuthForm from '../../components/AuthForm/AuthForm';
import styles from '../../styles/LoginPage.module.scss';

const Login: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthForm/>  
      
    </div>
  )
}

export default Login;
