import type { NextPage } from 'next'
import Head from 'next/head'
// import styles from '../../styles/AuthPage.module.scss';
import AuthForm from "../../hocs/AuthForm"
const Login: NextPage = () => {
  return (
    <div className="wrapper">
      <Head>
        <title>Авторизация</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthForm serviceName='login'/>
    </div>
  )
}

export default Login;
