
import { Breadcrumb, Layout, Menu  } from 'antd';
import { Content, Footer } from 'antd/lib/layout/layout';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import AdvertsList from '../../components/AdvertsList/AdvertsList';
import Header from '../../components/Header/Header';

const Adverts: NextPage = () => {
  const router = useRouter();
  return (
    <Layout style={{background:"#ffffff"}}>
    <Head>
      <title>Adverts</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Header activeTab={router.pathname}/>
    <Content className="site-layout" style={{ padding: '0 50px'}}>
      <h1 className='page-title'>Все объявления</h1>
      <AdvertsList/>
    </Content>
    <Footer style={{ textAlign: 'center' }}>My social: <a href="https://github.com/marcusblanco">GitHub</a></Footer>
  </Layout>
  );
};

export default Adverts;
