import { Content } from 'antd/lib/layout/layout';
import type { NextPage } from 'next';
import Head from 'next/head';
const Adverts: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Adverts</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
     
    </div>
  );
};

export default Adverts;
