import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import AdvertsList from '../../components/AdvertsList/AdvertsList';
import FilterForm from '../../components/Filter/Filter';
import { useDispatch, useSelector } from 'react-redux';
import { PlusOutlined } from '@ant-design/icons';
import { getAdvertsByQuery } from '../../api/Adverts';
import { setFilter } from '../../state/actions/filter';
import PageLayout from '../../components/PageLayout/PageLayout';
import { Button, Pagination } from 'antd';
import { useRouter } from 'next/router';

const Adverts: NextPage = () => {
  const router = useRouter();
  const [pagination, updatePagination] = useState({ current: 1 });
  const { adverts } = useSelector((state) => state.advertReducer);
  const filter = useSelector((state) => state.filterReducer);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(getAdvertsByQuery(filter));
  }, [filter]);
  useEffect(() => {
    dispatch(setFilter({ skip: filter.limit * (pagination.current - 1) }));
  }, [pagination.current]);
  const onChange = (page) => {
    updatePagination((state) => ({
      ...state,
      current: page,
    }));
  };
  return (
    <PageLayout>
      <Head>
        <title>Все объявления</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
        <FilterForm />
        <h1 className='page-title'>Все объявления</h1>
        <p>Найдено: {adverts.count}</p> 
        <Button style={{marginBottom:"20px"}} icon={<PlusOutlined />} onClick={()=>router.push(router.pathname +"/create")}>
          Добавить объявление
        </Button>
        <AdvertsList />
        {adverts.count > 0 && (
          <Pagination
            current={pagination.current}
            defaultPageSize={filter.limit}
            onChange={onChange}
            total={adverts.count}
            style={{ margin: '30px auto', width: 'fit-content' }}
          />
        )}
      </PageLayout>
  );
};

export default Adverts;
